### ISSUE TITLE
Suggestion to improve the body width

### ISSUE THREAD

**Issue by ooade** [shalvah/oldtweets.today#18]
Initial Phase (Feels normal):
![screenshot from 2019-02-18 04-52-01](https://user-images.githubusercontent.com/11811904/52927079-0154d500-3339-11e9-8907-af34f144f6dd.png)

With Content (Horizontal overflow mess):
![screenshot from 2019-02-18 04-53-20](https://user-images.githubusercontent.com/11811904/52927110-28130b80-3339-11e9-9044-c13d885e451f.png)

Why that happens is `viewport width` includes the scrollbar so it tends to overflow as the scroll bar (strange visitor) shows up on the page.

The fix:
Add `max-width` of 100%, or do without the width specified.

**Comment by shalvah** [comment]
Sure, you can go ahead if you'd like. Nothing uglier than a horizontal scrollbar (except Vim).
