### ISSUE TITLE
Option to select a date for throwback

### ISSUE THREAD

**Issue by frontendtony** [shalvah/oldtweets.today#20]
This should allow users to select a date they will like to see old tweets from, as opposed to only being able to see tweets from the current day

As requested by this user on [Twitter](https://twitter.com/Ibethia_cyn/status/1096744244004438016)

_One tiny bit of an issue is, there's no easy way to test the serverless function locally. I had to create my own GCP function to test the new feature_

PS: I have worked on this already in a fork of this repository

**Comment by shalvah** [comment]
Nice work. If you've already done this, you can go ahead to open a PR (with screenshots), so we can discuss the issue there.

**Comment by frontendtony** [comment]
Thanks. I have opened the PR [here](https://github.com/shalvah/oldtweets.today/pull/21)

**Comment by shalvah** [comment]
Done in #22 and #21
