### ISSUE TITLE
Update URL with selected date

### ISSUE THREAD

**Issue by shalvah** [shalvah/oldtweets.today#27]
As a follow-up to #20 and #21, it's important to keep the state of the app idempotent and reproducible by updating the URL with the date. We need to:

- update the page URL to include the day/month when a new one is selected. For simplicity, we can add a query parameter `?day=March+10`. (Note that I'm using a single field rather than day/month because it makes for a shorter client-side URL while still being easily parseable)
- have the page update the day when it loads based on the URL, similarly to what happens for username
- ensure that when the "share" button is clicked, the current URL with the date is shared (this should probably already be covered).

Of course, the day parameter can/should be omitted when no selection has been made by the user, in which case everything defaults to today.

**Comment by oneEyedSunday** [comment]
@shalvah [PR here](https://github.com/shalvah/oldtweets.today/pull/28)
