### ISSUE TITLE
Add Share functionality

### ISSUE THREAD

**Issue by shalvah** [shalvah/oldtweets.today#4]
It would be nice to have a Share button on the page, allowing users to share their results (probably with the hashtag). Unfortunately, putting it below the results will likely make users miss it. Putting it above might work, but we already have two lines of information there.

**Comment by BolajiAyodeji** [comment]
What contents should the share hold?
Something like: `I just checked what I tweeted on this day in the past with #oldtweets.today, check your's here. .`  ?
Preferred social media?

**Comment by shalvah** [comment]
"Share to Twitter"

Contents should be something like: "Here's my #TwitterThrowback. Check
yours here", then link to oldtweets.today/#their-username

**Comment by BolajiAyodeji** [comment]
Okay! Let me work on this.
`#their-username` here should be the sharer's username or the username checked via the app?

**Comment by Lekky71** [comment]
Cool, question though, "Here's my #TwitterThrowback...", what does it return exactly? A link to the throwback tweet? If so, what about if the throwback tweets are more than one.

**Comment by BolajiAyodeji** [comment]
I think it should just link back to the app, there might be no need of adding the user's throwback.
More like
`"Here's my #TwitterThrowback. Check yours here", then link to oldtweets.today`
What do you think?

**Comment by shalvah** [comment]
"Here's my Twitter throwback" implies that you're linking them to your
results. So the link should be #<your-username>
That takes them to a page with your username filled in, so they just need
to click the button. They can also replace the username with theirs and
check.

**Comment by Lekky71** [comment]
Oh, cool.
The search form query can be made automatically 'on page load' since the username is already filled in, so once someone that clicked on the shared link sees the throwback; they can just edit the text field with their Twitter username to see theirs.

**Comment by Lekky71** [comment]
@shalvah Twitter doesn't allow hashtags in their tweet-to link, there's a query that accepts hashtags,
What this means is that http://oldtweets.today/#${window.username} would not be possible.
This is a blocker.

**Comment by shalvah** [comment]
Okay, no problem. We can do http://oldtweets.today/?username=${window.username}. The code already supports that.

**Comment by shalvah** [comment]
> Oh, cool.
> The search form query can be made automatically 'on page load' since the username is already filled in, so once someone that clicked on the shared link sees the throwback; they can just edit the text field with their Twitter username to see theirs.

Yes, we could do that too. Submit the form when the page is loaded with a preset value.

**Comment by Lekky71** [comment]
Cool

**Comment by shalvah** [comment]
Closed in #7
