### ISSUE TITLE
Feature: store last used username in local storage

### ISSUE THREAD

**Issue by shalvah** [shalvah/oldtweets.today#40]
...and prefill the text box on page load.

That way, a frequent user won't have to retype their handle each time.

Note: if the page is visited with a query parameter `username=<username>`, that should overwrite the last used username (until the user types something else).

**Comment by calebdeji** [comment]
Hi Shalvah, I would like to raise a pull request for this.

**Comment by shalvah** [comment]
Sure, go ahead.

**Comment by calebdeji** [comment]
Hi Shalvah, I wanted to make a PR now but I noticed there are a lot of changes made due to formatting, I think it would be preferable to have a base formatter configuration like .prettierc.

Is it okay to still make the PR?

**Comment by shalvah** [comment]
Errr... I'd prefer to have it without the formatting changes. Disable Prettier or whatever you use for the project and make your changes.

**Comment by calebdeji** [comment]
> Errr... I'd prefer to have it without the formatting changes. Disable Prettier or whatever you use for the project and make your changes.

Okay.

**Comment by shalvah** [comment]
Closed in #41
