### ISSUE TITLE
Improve button and input  styling

### ISSUE THREAD

**Issue by shalvah** [shalvah/oldtweets.today#6]
When the search is running, the button is disabled, but there are no styles or the ":disabled" state, so the UI doesn't reflect this.

Also, it would be ideal if the button moves below the search bar on mobile (so the input's placeholder text isn't truncated). In such a case, we'd need to round out all the borders of both input and button.

**Comment by BolajiAyodeji** [comment]
I thought as much.
Would look into this

**Comment by adedayomoshood** [comment]
> When the search is running, the button is disabled, but there are no styles or the ":disabled" state, so the UI doesn't reflect this.
> 
> Also, it would be ideal if the button moves below the search bar on mobile (so the input's placeholder text isn't truncated). In such a case, we'd need to round out all the borders of both input and button.

I have created a PR to fix this #14

**Comment by shalvah** [comment]
This issue is still open, if anyone's interested. The button doesn't change appearance when in the disabled state, and neither does its pointer.

**Comment by oneEyedSunday** [comment]
I created a PR for updated the button while its disabled due to fetching. [Here](https://github.com/shalvah/oldtweets.today/pull/24)

**Comment by shalvah** [comment]
Thanks @oneEyedSunday
