### ISSUE TITLE
Cannot find tweets with my username

### ISSUE THREAD

**Issue by Billmike** [shalvah/oldtweets.today#8]
Can't find tweets tweeted under my username for February 16, even though there are.
<img width="1440" alt="screenshot 2019-02-16 at 6 33 06 pm" src="https://user-images.githubusercontent.com/24798364/52903134-d45dd080-3219-11e9-8083-d94e2370801d.png">

**Comment by UcheSylvester** [comment]
That's actually because you don't have any tweets on the February 16th. The tweets that are fetched are from the previous years. The current year is not included. 
I think that's why it's called #TwitterThrowback

**Comment by Billmike** [comment]
Oh! Now I get it. That does make sense then. Thanks. Closing now
