### ISSUE TITLE
Show different message for usernames not found on Twitter

### ISSUE THREAD

**Issue by UcheSylvester** [shalvah/oldtweets.today#9]
I think it'd be nice if we had a different message for usernames that are not found on Twitter. 
Currently, the same error message (Sorry, we couldn't find any tweets by username on February 16😕) is showing for both incorrect usernames and users without tweets on the said date!
Having something like "username not found (on Twitter)!" or "please check the username and try again" would be nice. Where username is name inputted to be searched.
This will help anyone using the app know they are searching for an incorrect username hence improving users' experience!

**Comment by shalvah** [comment]
Unfortunately, it's impossible to determine either on our end. Twitter's
search will return no results for both those conditions, so we can't detect.

I feel the user experience is alright. The username and day are highlighted
in bold, so you can take a look at the username and double-check your
spelling.
